// <auto-generated />
using System;
using Foodie.Persistance.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Foodie.Persistance.EntityFramework.Migrations
{
    [DbContext(typeof(FoodieDbContext))]
    [Migration("20221217095820_AddIngridient")]
    partial class AddIngridient
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Foodie.Domain.Ingridient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipieId");

                    b.ToTable("Ingridient");
                });

            modelBuilder.Entity("Foodie.Domain.Recipie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipieRatingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipieRatingId");

                    b.ToTable("Recipies");
                });

            modelBuilder.Entity("Foodie.Domain.RecipieRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("RecipieRating");
                });

            modelBuilder.Entity("Foodie.Domain.Ingridient", b =>
                {
                    b.HasOne("Foodie.Domain.Recipie", "Recipie")
                        .WithMany("Ingridients")
                        .HasForeignKey("RecipieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipie");
                });

            modelBuilder.Entity("Foodie.Domain.Recipie", b =>
                {
                    b.HasOne("Foodie.Domain.RecipieRating", "RecipieRating")
                        .WithMany()
                        .HasForeignKey("RecipieRatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipieRating");
                });

            modelBuilder.Entity("Foodie.Domain.Recipie", b =>
                {
                    b.Navigation("Ingridients");
                });
#pragma warning restore 612, 618
        }
    }
}
